# Database connection information
# Uses an in-memory database by default.
# This database is saved in a file next to this config file by default.
#
# The following substitutions are available:
#
# $dataFolder     -     Is replaced with the absolute path of the data folder of this plugin at runtime
#
# The default driver is for the SQLite database file.
# To use MySQL, use com.mysql.jdbc.Driver and fill in the url as described here:
# https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html

username: ProxieTV
driver: org.mariadb.jdbc.Driver
password: Florian12
url: jdbc:mariadb://proxietv.de:3306/nisled